/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author Root
 */
public class TelaPrincipalLavajato extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalLavajato
     */
    public TelaPrincipalLavajato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarTelaPrincipal = new javax.swing.JMenuBar();
        jMenuClientes = new javax.swing.JMenu();
        jMenuItemCadastroClientes = new javax.swing.JMenuItem();
        jMenuItemListaCliente = new javax.swing.JMenuItem();
        jMenuEstoque = new javax.swing.JMenu();
        jMenuItemCasdatroProduto = new javax.swing.JMenuItem();
        jMenuItemListaProduto = new javax.swing.JMenuItem();
        jMenuItemCadastroFornecedor = new javax.swing.JMenuItem();
        jMenuItemListaFornecedor = new javax.swing.JMenuItem();
        jMenuContorleCaixa = new javax.swing.JMenu();
        jMenuItemFluxoCaixa = new javax.swing.JMenuItem();
        jMenuItemContasPagarDispesas = new javax.swing.JMenuItem();
        jMenuItemContasReceber = new javax.swing.JMenuItem();
        jMenuControleInterno = new javax.swing.JMenu();
        jMenuItemCastroFuncionario = new javax.swing.JMenuItem();
        jMenuItemListaFuncionario = new javax.swing.JMenuItem();
        jMenuItemContorleHora = new javax.swing.JMenuItem();
        jMenuAgenda = new javax.swing.JMenu();
        jMenuItemAgendar = new javax.swing.JMenuItem();
        jMenuItemAgendaDiaria = new javax.swing.JMenuItem();
        jMenuSairModulo = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuClientes.setText("Clientes");

        jMenuItemCadastroClientes.setText("Cadastro de clientes");
        jMenuClientes.add(jMenuItemCadastroClientes);

        jMenuItemListaCliente.setText("Lista clientes");
        jMenuClientes.add(jMenuItemListaCliente);

        jMenuBarTelaPrincipal.add(jMenuClientes);

        jMenuEstoque.setText("Estoque");

        jMenuItemCasdatroProduto.setText("Cadastro de produtos");
        jMenuEstoque.add(jMenuItemCasdatroProduto);

        jMenuItemListaProduto.setText("Lista de produtos");
        jMenuEstoque.add(jMenuItemListaProduto);

        jMenuItemCadastroFornecedor.setText("Cadastro de fornecedor");
        jMenuEstoque.add(jMenuItemCadastroFornecedor);

        jMenuItemListaFornecedor.setText("Lista fornecedor");
        jMenuEstoque.add(jMenuItemListaFornecedor);

        jMenuBarTelaPrincipal.add(jMenuEstoque);

        jMenuContorleCaixa.setText("Controle do caixa");

        jMenuItemFluxoCaixa.setText("Fluxo de caixa");
        jMenuContorleCaixa.add(jMenuItemFluxoCaixa);

        jMenuItemContasPagarDispesas.setText("Contas a pagar/dispesas");
        jMenuContorleCaixa.add(jMenuItemContasPagarDispesas);

        jMenuItemContasReceber.setText("Contas a receber");
        jMenuContorleCaixa.add(jMenuItemContasReceber);

        jMenuBarTelaPrincipal.add(jMenuContorleCaixa);

        jMenuControleInterno.setText("Controle interno");

        jMenuItemCastroFuncionario.setText("Cadastro de funcionarios");
        jMenuItemCastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCastroFuncionarioActionPerformed(evt);
            }
        });
        jMenuControleInterno.add(jMenuItemCastroFuncionario);

        jMenuItemListaFuncionario.setText("Lista de funcionarios");
        jMenuControleInterno.add(jMenuItemListaFuncionario);

        jMenuItemContorleHora.setText("Controle horas trabalhadas/veiculos lavados");
        jMenuControleInterno.add(jMenuItemContorleHora);

        jMenuBarTelaPrincipal.add(jMenuControleInterno);

        jMenuAgenda.setText("Agenda");

        jMenuItemAgendar.setText("Agendar");
        jMenuAgenda.add(jMenuItemAgendar);

        jMenuItemAgendaDiaria.setText("Agenda Diaria");
        jMenuAgenda.add(jMenuItemAgendaDiaria);

        jMenuBarTelaPrincipal.add(jMenuAgenda);

        jMenuSairModulo.setText("Sair do modulo lavajato");

        jMenuItemSair.setText("Sair");
        jMenuSairModulo.add(jMenuItemSair);

        jMenuBarTelaPrincipal.add(jMenuSairModulo);

        setJMenuBar(jMenuBarTelaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCastroFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCastroFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalLavajato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalLavajato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalLavajato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalLavajato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalLavajato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAgenda;
    private javax.swing.JMenuBar jMenuBarTelaPrincipal;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuContorleCaixa;
    private javax.swing.JMenu jMenuControleInterno;
    private javax.swing.JMenu jMenuEstoque;
    private javax.swing.JMenuItem jMenuItemAgendaDiaria;
    private javax.swing.JMenuItem jMenuItemAgendar;
    private javax.swing.JMenuItem jMenuItemCadastroClientes;
    private javax.swing.JMenuItem jMenuItemCadastroFornecedor;
    private javax.swing.JMenuItem jMenuItemCasdatroProduto;
    private javax.swing.JMenuItem jMenuItemCastroFuncionario;
    private javax.swing.JMenuItem jMenuItemContasPagarDispesas;
    private javax.swing.JMenuItem jMenuItemContasReceber;
    private javax.swing.JMenuItem jMenuItemContorleHora;
    private javax.swing.JMenuItem jMenuItemFluxoCaixa;
    private javax.swing.JMenuItem jMenuItemListaCliente;
    private javax.swing.JMenuItem jMenuItemListaFornecedor;
    private javax.swing.JMenuItem jMenuItemListaFuncionario;
    private javax.swing.JMenuItem jMenuItemListaProduto;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSairModulo;
    // End of variables declaration//GEN-END:variables
}
